on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8888"
  DRUPAL_CORE_VERSION: 9.3.x
  SYMFONY_DEPRECATIONS_HELPER: disabled
  BROWSERTEST_OUTPUT_DIRECTORY: 'sites/simpletest'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0']
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:${{ matrix.php-versions }}-alpine

    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set Drupal root
        run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Set module folder
        run: echo "MODULE_FOLDER=$DRUPAL_ROOT/modules/contrib/${{ secrets.MODULE_NAME }}" >> $GITHUB_ENV

      - name: Clone drupal
        run: git clone --depth 1 --branch "$DRUPAL_CORE_VERSION" http://git.drupal.org/project/drupal.git/ $DRUPAL_ROOT

      - name: Install required composer dependencies
        run: |
          cd $DRUPAL_ROOT
          composer config platform.php ${{ matrix.php-versions }}
          composer config repositories.4 composer https://repository.drupal.hel.ninja/
          composer config repositories.5 path $GITHUB_WORKSPACE
          composer require drupal/${{ secrets.MODULE_NAME }} -W
          composer run-script drupal-phpunit-upgrade
          composer require "drush/drush ^10.0"
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require --dev donatj/mock-webserver
          composer require --dev "drupal/coder"

      - name: Install Drupal
        run: |
          cd $DRUPAL_ROOT
          php -d sendmail_path=$(which true); vendor/bin/drush --yes -v site-install minimal --db-url="$SIMPLETEST_DB"
          vendor/bin/drush en ${{ secrets.MODULE_NAME }} -y

      - name: Run PHPCS
        run: |
          cd $DRUPAL_ROOT
          vendor/bin/phpcs $MODULE_FOLDER --standard=Drupal --extensions=php,module,inc,install,test,info

      - name: Start services
        run: |
          cd $DRUPAL_ROOT
          vendor/bin/drush runserver $SIMPLETEST_BASE_URL > /dev/null 2>&1 &
          chromedriver --port=4444 > /dev/null 2>&1 &

      - name: Run PHPUnit tests
        run: |
          cd $DRUPAL_ROOT
          php -d pcov.directory=$MODULE_FOLDER \
            vendor/bin/phpunit \
            --bootstrap $DRUPAL_ROOT/core/tests/bootstrap.php \
            -c $MODULE_FOLDER/phpunit.xml \
            --coverage-clover=coverage.xml \
            $MODULE_FOLDER
          codecov

      - name: Create an artifact from test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: results
          path: |
            ${{ env.DRUPAL_ROOT }}/sites/simpletest/browser_output/
            ${{ env.DRUPAL_ROOT }}/coverage.xml
          retention-days: 1
