on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8888"
  SYMFONY_DEPRECATIONS_HELPER: disabled
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1']
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:${{ matrix.php-versions }}-alpine

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set variables
        run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Build project
        run: composer create-project city-of-helsinki/drupal-helfi-platform:dev-main $DRUPAL_ROOT --no-interaction --repository https://repository.drupal.hel.ninja/

      - name: Install Drupal
        run: |
          cd $DRUPAL_ROOT
          php -d sendmail_path=$(which true); vendor/bin/drush --yes -v site-install minimal --db-url="$SIMPLETEST_DB"

      - name: Update modules
        run: |
          cd $DRUPAL_ROOT
          composer config repositories.5 path $GITHUB_WORKSPACE
          composer require drupal/${{ secrets.MODULE_NAME }}
          vendor/bin/drush en ${{ secrets.MODULE_NAME }} -y

      - name: Run PHPCS
        run: |
          cd $DRUPAL_ROOT
          vendor/bin/phpcs public/modules/contrib/${{ secrets.MODULE_NAME }} --standard=Drupal

      - name: Run PHPUnit tests
        run: |
          cd $DRUPAL_ROOT
          vendor/bin/drush runserver $SIMPLETEST_BASE_URL > /dev/null 2>&1 &
          chromedriver --port=4444 > /dev/null 2>&1 &
          vendor/bin/phpunit --fail-on-skipped -c $DRUPAL_ROOT/phpunit.platform.xml --verbose --group ${{ secrets.MODULE_NAME }}
